### ISSUE TITLE
Trying to find documentation on how to use this plugin

### ISSUE THREAD

**Issue by Helios747** [lichie567/XIVAuras#23]
Hello,

I'm trying to use this plugin as a replacement for Caraxi's no longer maintained RemindMe, which does what this does, tracking of buffs/debuffs. But I for the life of me cannot figure out how to set anything in this up.

I tried to start with something extremely simple. Track the status of Reaper's Death's Design on target.

I aimed for it to just show a big red square, anything at all, when the debuff was applied to target

But nothing shows up, when the debuff is on or off.

Is there any documentation for this? This UI is difficult to figure out.

![icon](https://i.imgur.com/Qm0cxwn.png)

![trigger](https://i.imgur.com/63i0qsR.png)

**Comment by Rho003** [comment]
As of now, there is little documentation. This is partially inspired by WeakAuras from WoW, and tries to get somewhat similar functionality. Since it is still pretty early in development, it is kind of assumed you either have experience with weakauras, or you understand programming logic.

The visibility page is just to decide which situations the aura should hide, and for which classes it loads. The default shoulde be all classes.

The icon page decides what the baseline aura should look like if no conditions are met.

The trigger page is where you use if/and/or/xor logic to decide what should load the aura. This can be a single trigger or many triggers, either a or b, but not both etc. It is not identical to regular programming if/and/or logic. This can be buffs, debuffs, existance of a cooldown, count of stacks, usability, state of general resources (aka not class specific resources as of now, hopefully soon)

The condition page is for special conditions where the aura will change. This can be triggered by cooldown timer (value), stacks of buff (Stacks), Health (HP), Mana (MP) etc. compared to a static value. The order of the conditions (when you have more than one) matter for how it will look, because it reads line by line. A lower condition will always be tested later. Conditions are usually used to show/hide on condition, grey out aura, change icon size or which icon that will show etc, change border.

The Labels page are for text written on the icons. This is for timer or custom text you want to trigger.

For Death's Design the way you described, this should work. It will only work while targeting the guy with the debuff. the moment you aren't targeting him anymore, it will lose it's trigger condition.

7FjbbhoxEP0VZFVqK20QS2iV8JaAktCSgEKUpEWoNYsBK8sa2d4ktMqX9aGf1F/o+LI3oGzUXIgUXlg8Ox7PHs/MGfvPr98/0Rs5mxJURZeN872QY1FMfg85C6fIQWdao+wgJWxSIVF1ybwaC4Z0VIx0zBBmn+CJ0tNKMDTPanflyg2PBfHCJQepcUfOfGKtrlh/XtVBbSaopGAwNaszE5JMiifhhHDqieI58STjZadgX7Q5vcaSgFFOmrQPVi7BkSK48kU/7xzUoT/Ig01WIpsVa3TMbvYZHxCOqpKHxEFmdDam3lVABCDnRrIa8xlfBYV5GDUHGX/yPa7cGwQHfbXPC3AL/Lcf0OZsxMHXzg1V6wyxL+BDMtLWFHtUztT0j7C9wTXhMquuDGlJk8J3L1hR0vUA4FoAXAuAmwUg7WBq1yB76kRgCe5JosM7+qIYCm1IvWpNTbhuO6gWCskmRt8t75YBrBpnUyMwAaL+rxeJpaEAUDRxn/ipWrDCvzlVpxAp2Iqh3+eWDa0V1w2ATwvuWTgWdMEOuZUHjE8wVDzUvcZ+SKqy93QlpY05CeRe4I3V7pSMA3s+HQV6dMAC2ajrCqD+fiYQNKhPR1sBYwOfbEnGvpUr1u8XmRwqqVuh9CE3ovC1wxdZzE4MdSk4kfLeBsdA771Y5e2c6ne3282LtyTme71M/FsvUgtDEUh50b2vGw/yosNC7hk2bk3141zlg8VMW3hIdq09qezfTVI9c1Jlhj0QnFNB+9QHSsyv2Qu6wBb+DZ6JIzpIWgk1aABHTvoq1FLCVigFPP79ph4qYk7JL8bUJ23ChxC3NBjNLXHI/AEJOjj0VP+WamQgzD+xvqIlyNdSROsg6kiuzaj4j4Wmxe72YnCSz0whZtLvzlkjIwqJvSvxqIS45a5I3p1M8u4kyVtelbyltTLiPfrll8SIOQS+YcTGAiOWDSNWYkbUmG0YcdNmbhjxWRmxo+nIdBFnnI5G6o4kj+TOMopwSscSW5npFs1/cybP67bhfC+iyfHUqE64scT6WydYjt+KAlwMKEJLO20adtNtB/7sOEUPdXWFoF9aOCOBKkLbyTDbngMyNRYGSZeTiOy8RJCemfUlvpBb/CaF23J0jog/JVwU04rxni1g0BhARf2wo26F0rcex/jWbq+OFujYmNLs9mC3e49+Npu7RPz/o9mraGjdZel72j5dksHbuzk5nI2Hwrv9cDh8b1JaX0fnQ5hSy+zVEx0vT4zf5q78Nex26XGK9Vzi3/0FAAD//wMA

This one uses cropped icon of the Death's Design debuff: 

 7FjbbhoxEP0VZFVqK20QS2iV8JaAktCSgEKUpEWoNYsBK8sa2d4ktMqX9aGf1F/o+LI3oGzUXIgUXlg8Ox6fHc/MGfvPr98/0Rs5mxJURZeN872QY1FMfg85C6fIQWdao+wgJWxSIVF1ybwaC4Z0VIx0zBBmn+CJ0tNKMDTPanflyg2PBfHCJQepcUfOfGKtrlh/XtVBbSaopGAwNaszE5JMiifhhHDqieI58STjZadgX7Q5vcaSgFFOmrQPVi4BSBGgfNHPOwd16A/yYJOVyGbFGh2zm33GB4SjquQhcZAZnY2pdxUQAZ5zI1mN+YyvcoV5GDUHGTz5iCv3doKDvtrnBcAC/PYD2pyNOGDt3FC1zhD7Aj4kI21NsUflTE3/CNsbXBMus+rKkJY0KXz3ghUlXY8DXOsA1zrAzTogDTC1a5A9dSKwBHiS6PCOvih2hTakXrWmJlxhp2uhkGxi9N3ybhmcVeNsagQmQNT/9XpiaSiAK5q4T/xULViBb07VKUQKtmLo97llQ2vFdWPbIrhn4VjQBTvkVh4wPsFQ8VD3Gvshqcre05WUNuYkkHuBN1a7UzIA9nw6CvTogAWyUddxof5+JhA0qE9HWwFjA59sSca+lSsW94tMDpXUrVD6kBtR+NrhiyxmJ4a6lDuRQm+DY6D3XqxCO6f63e128+ItifleLxP/FkVqYSgCKRTd+8J4EIoOC7ln2Lg11Y9zlQ/WZ9rCQ7Jr7Ull/26S6pmTKjPsgeCcCtqnPlBifs1e0AW28G/wTBzRQdJKqEEDOHLSV6GWErZCKeDx7zf1UBFzSn4xpj5pEz6EuKXBaG6JQ+YPSNDBoaf6t1QjA2H+ifUVLUG+liJaB1FHcm1GxX8sNC12txc7J/nMlMdM+t05a2REIbF3JR6VELfcFcm7k0nenSR5y6uSt7RWRrxHv/ySGDGHwDeM2FhgxLJhxErMiNpnG0bctJkbRnxWRuxoOjJdxBmno5G6I8kjubOMIpzSscRWZrpF89+cyfO6bTjfi2hyPDWqE24ssXjrBMvxW1GAiwFFaGnQpmE33Xbgz45T9FBXVwj6pXVnJFBFaDsZZttz8EyNhUHS5SQiOy8RpGdmscQXcovfpPy23DtHxJ8SLoppxXjPFnzQGEBF/bCjboXStx7H+NZur44W6NiY0uz2YLd7j342m7tE/P+j2atoaN1l6XvaPl2Swdu7OTmcjYfCu/1wOHxvUlpfR+e7MKWW2asnOl6eGNzmrvw17HbpcYr1XOLf/QUAAP//AwA=

If you want to remove the timer and just have the icon, go on Labels -> Value ->Remove [value:t] from Text Format

**Comment by lichie567** [comment]
If anyone needs help using the plugin, you can join this discord to ask questions: https://discord.gg/delvui
